### ISSUE TITLE
Save Errors

### ISSUE THREAD

**Issue by charliejulloa** [BattleMapp/BattleMapp.io#16]
When a map is saved without a title (e.g. the title is left blank), the "Saving Map" prompt triggers and does not go away. The map is not saved in this case. A prompt indicating that a map title is required is suggested.

It also appears that maps are automatically over-written before the prompt to overwrite them occurs, but I'm not 100% certain this occurs.

**Comment by BattleMapp** [comment]
Gold star for your help! Thanks so much - I've just fixed this one but will close once it's uploaded.

Can I add your username into the random name generator for your help? If so, let me know what like ie "Charlie" "Charlie-Julloa" etc...
