### ISSUE TITLE
Saving error with removing dirt.

### ISSUE THREAD

**Issue by rizy2001** [BattleMapp/BattleMapp.io#24]
After removing dirt that was placed by the dirt brush i found i could no longer save a map. I can save after using the dirt brush, but as soon as i remove only one piece of dirt i get an infinite saving popup, and nothing happens. (I let it run for about 5 minutes but nothing happened.) 

Furthermore the removing of placed dirt is a bit clunky in and of itself, with dirt sometimes becoming untargetable. This can be solved by pressing generate flat terrain repeatedly, up until you have no terrain anymore and then you can target the dirt again. It could also be occasionally be targeted by going down a layer or two, but sometimes dirt still remained. 

I must say i really enjoy using this tool, and i can't wait to see what you do with it!

**Comment by BattleMapp** [comment]
Thanks so much! I found the bug and just fixed it on the backend. Can I add "Rizy" to the random name generator as a thanks?

**Comment by rizy2001** [comment]
> Thanks so much! I found the bug and just fixed it on the backend. Can I add "Rizy" to the random name generator as a thanks?

This is a little late, but yes please!
