### ISSUE TITLE
When Editing 'Map Size X' & 'Map Size Y' for A Pre-Generated Map, Die Spawns

### ISSUE THREAD

**Issue by Grendel580** [BattleMapp/BattleMapp.io#26]
When editing the generated landscapes size, whenever you press a key corresponding to a die (4 = d4, 6 = d6, etc.) it spawns a die, dropping it.
![image](https://user-images.githubusercontent.com/78511835/107793211-a97cb900-6d1b-11eb-98c0-0f74e6410286.png)
![image](https://user-images.githubusercontent.com/78511835/107793262-b39eb780-6d1b-11eb-94b5-3479d4406d3c.png)
![image](https://user-images.githubusercontent.com/78511835/107793302-c0bba680-6d1b-11eb-8065-41bd02020d1b.png)

I'm using the latest build for testing this issue.

**Edit: Looks to be spawning die for all fields.**

**Comment by BattleMapp** [comment]
Thank you! Just fixed on the backend.
