### ISSUE TITLE
Ball spells in the effects menu

### ISSUE THREAD

**Issue by Valdemar-of-Westgate** [BattleMapp/BattleMapp.io#31]
Would it be possible to add a semi transparent semi sphere (flat side on the floor) to the effects menu for use as a ball spell effect. Alternatively a sphere set with its centre on the ground level so by default you only see a semi sphere. The latter would work better on the sloped terrain as the ball spells flower differently on slopes.

**Comment by BattleMapp** [comment]
Yes! I believe this has been done. Thanks!
