### ISSUE TITLE
Cannot change an asset's layer once placed

### ISSUE THREAD

**Issue by rm-rstar** [BattleMapp/BattleMapp.io#34]
Once an item is placed, I have to be on the same layer to select it, which can be difficult to determine. Once selected I cannot then change layers to move the object up or down a layer. This is particularly and issue because there are many object place within a house that cannot be individually selected in the menus to be placed.

**Comment by BattleMapp** [comment]
Ah good idea - I believe I have fixed this issue in the newest update coming today BUT you can use the up/down arrows to raise/lower layers, meaning you can pick up an object, move the ground layer with the arrows and place it wherever you like.
