### ISSUE TITLE
When generating a random dungeon the levels keep increasing

### ISSUE THREAD

**Issue by Valdemar-of-Westgate** [BattleMapp/BattleMapp.io#38]
Every time you click on the random dungeon generator (both on and off) the level increases by 3 so when using this to find a suitable dungeon the level keeps increasing. I stopped testing at level -60 (but this was 60 levels above the starting plane level). The level arrows don't then work properly (see screen capture where the arrows have changed the level back to level 0).
![Capture](https://user-images.githubusercontent.com/79011977/109003718-b4323900-769f-11eb-9ab6-5b902f08ed76.JPG)

**Comment by BattleMapp** [comment]
Ah thanks for this, fixed in the update coming today!
