### ISSUE TITLE
Everything is blurry, text is unreadable

### ISSUE THREAD

**Issue by MyrtoDnD** [BattleMapp/BattleMapp.io#39]
The last two releases are not usable for me.   Releases before that are fine.   Nothing changed with my PC setup.  Battlemapp looks 'out of focus'.  Everything is affected, tokens, buildings, trees, etc.  It is most noticable for the small text which is fuzzy to the point of being unreadable.

**Comment by BattleMapp** [comment]
That's odd - standalone version or browser version? If standalone have you tried changing the resolution (menu, settings, resolution)?

**Comment by MyrtoDnD** [comment]
I was using the standalone version.   I was able to change the resolution,
as recommended.  It was defaulting to the lowest setting, causing the
blurring.   Setting it back to the highest resolution has fixed the issue.
