### ISSUE TITLE
Saved maps does not save structure

### ISSUE THREAD

**Issue by SaguarOhm** [BattleMapp/BattleMapp.io#4]
Hello there. I'm a new supporter using 210203 version and tried saving a battlemap I had created. I used buildings, characters, walls, trees, grass, and rocks, dirt brush and clear skies, grass 60x80 map. upon saving and reloading, everything but the structures and dirt brush objects loaded. I want to say it's a blast to be a patron and to use this software. huge props to the development team! Thank you again!
![Cherryvale - after](https://user-images.githubusercontent.com/56621347/106743835-b985f180-65d3-11eb-924b-f9026c8a4baf.png)
![Cherryvale before](https://user-images.githubusercontent.com/56621347/106743871-c9053a80-65d3-11eb-947c-074286f3c20f.png)

**Comment by BattleMapp** [comment]
Perfect report, thank you! Issue has been fixed so feel free to get the latest link: https://www.patreon.com/posts/47059676
