### ISSUE TITLE
Certain props do not persist across save and restart

### ISSUE THREAD

**Issue by samwestenberg** [BattleMapp/BattleMapp.io#40]
Hello!  First of all -- awesome tool, very excited to see how it evolves over time.  I noticed that some props don't seem to persist on the map across saving + restarting the standalone app.  The 'ladder' prop in particular is where I am noticing this right now.  If I save the map and re-load it without restarting battlemapp, the ladder is still where I left it.  If I restart battlemapp and reload the map, though, the ladder is gone.  I added another random prop (a cart) and it does persist correctly when I restart battlemapp.

**Comment by BattleMapp** [comment]
Thank you! I believe I have fixed this in the next update!
