### ISSUE TITLE
Suggestion: Exporting and New Map

### ISSUE THREAD

**Issue by 19Dawgmeat** [BattleMapp/BattleMapp.io#41]
Not an issue, or maybe it can be, but a recommendation.  Right now the only way to export in the stand alone is to take a screencapture.  I'd love the functionality to just export the map you created and if I need to do any cropping I can do it in an image editor.  This way I can have an oversized map where I don't lose any details then resize as needed.

Additionally, it would be super awesome if we have a "New" option in settings so I don't have to quit the app and reload it every time I wanted to work on something else.

**Comment by BattleMapp** [comment]
Thanks! I'll update the export functionality for the next update. 

You could click "clear" map, which clears the scene. It almost does the same job as new map button!
