### ISSUE TITLE
Can't change the color of the simple 3d tokens

### ISSUE THREAD

**Issue by holbie** [BattleMapp/BattleMapp.io#42]
First off, I love this program. I'm a brand new DM, and this was a really good way for me to bring certain encounters to life. Before the March update, I was able to change the color of the simple 3d tokens via the token menu. The menu still comes up, but I am unable to make the color changes. Any advice would be appreciated.

Thanks!

**Comment by BattleMapp** [comment]
Ah thanks! You meant he simple shapes? You're right and I've just fixed this ready for the next update!
