### ISSUE TITLE
Water terrain feature breaking

### ISSUE THREAD

**Issue by rm-rstar** [BattleMapp/BattleMapp.io#43]
The new water table/terrain will break, causing it to render invisibly and cause odd visual artifacts.
Build: 210312 Standalone Experimental
Steps to replicate:
Launch app, go to terrain generator, add some height value, generate terrain, check the add water table radio button, adjust water table y height until visible, go to world setting, under the fog dropdown menu select some fog. At this moment the water will disappear but will continue to affect the way object under it render, such as the fog.

**Comment by BattleMapp** [comment]
Thank you! I've just fixed this so will update the build link on Patreon ASAP.
