### ISSUE TITLE
Maps Not Preserved Between Closing/Opening Standalone Application

### ISSUE THREAD

**Issue by Grendel580** [BattleMapp/BattleMapp.io#5]
When saving a map, it reloads correctly while the application is still running.
![BattleMapp 2021-02-03_16-37-37](https://user-images.githubusercontent.com/78511835/106922853-14ead900-66d3-11eb-897b-1b24fc65d009.png)

After closing the application, and reloading it, most items (except for character models, prop models, world settings) disappear.
![BattleMapp 2021-02-03_16-39-07](https://user-images.githubusercontent.com/78511835/106923020-45327780-66d3-11eb-90d1-38295aff7319.png)

Apologies if this has already been documented or we're not intended to close/reopen the application between loads. This was done using the Standalone C version.

**Comment by BattleMapp** [comment]
Thank you! I believe I have fixed this issue in the latest build here: https://www.patreon.com/posts/47059676

**Comment by Grendel580** [comment]
Couple quick notes: Still using generated maps, after saving map, exiting application, reloading application, paths are not retained and rocks change climate texture (for example from sandy rock to mossy rock).

I tested this using the latest 20210204 B build.
