### ISSUE TITLE
After Selecting A Small Rock and Rotating, All Future Props, Tokens, Models, Effects, Lights Come in Tilted

### ISSUE THREAD

**Issue by Grendel580** [BattleMapp/BattleMapp.io#7]
![image](https://user-images.githubusercontent.com/78511835/106965158-d2dc8a00-6708-11eb-9c2f-9b108d8787dc.png)

20210204 Standalone Build B. Non-Generated map.

**Comment by Grendel580** [comment]
Only seems to affect place able objects. Not paint-brush like effects. Further looking at it, if you swap back to another tool like the trees or large rocks, it fixes the place able item orientation. Even when rotating (as it looks like these rotate around a vertical axis). The small rocks rotating will break it again (as it looks like they rotate around a horizontal axis).

**Comment by BattleMapp** [comment]
This is an absolutely amazing bug that no one else has picked up on yet - thanks it's an easy fix and will be updated later/tomorrow. I'm going to put your name "Grendel" in the random name generator for your contribution so far!

**Comment by Grendel580** [comment]
Thanks! That's really cool, I appreciate it! I'll keep trying to break things here and there.

**Comment by BattleMapp** [comment]
This issue should be fixed in the latest upload here: https://www.patreon.com/posts/47059676
