### ISSUE TITLE
Deleted Items After Reloading Cont'd.

### ISSUE THREAD

**Issue by Grendel580** [BattleMapp/BattleMapp.io#8]
Couple quick notes: Still using generated maps, after saving map, exiting application, reloading application, paths are not retained and rocks change climate texture (for example from sandy rock to mossy rock).

I tested this using the latest 20210204 B build.

_Originally posted by @Grendel580 in https://github.com/BattleMapp/BattleMapp.io/issues/5#issuecomment-773640308_

**Comment by BattleMapp** [comment]
Thank you, just fixed this on the backend,
